import type { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiFramer,
  SiGreensock,
  SiMysql,
  SiPostgresql,
  SiHtml5,
  SiCss,
  SiStorybook,
  SiGithubactions,
  SiDocker,
  SiGit,
  SiTypescript,
  SiTailwindcss,
  SiNestjs,
  SiJsonwebtokens,
  SiRedis,
  SiReactquery,
  SiMongodb,
  SiRabbitmq,
  SiMinio,
  SiJest,
  SiZod,
  SiFigma,
} from "react-icons/si";

export type NodeSize = "large" | "medium" | "small";

export interface TechNode {
  name: string;
  icon: IconType;
  /** Official brand color, used at full saturation when active. */
  color: string;
  size: NodeSize;
  note: string;
  pairsWith: string[];
  /** Resting position as a percentage of the cluster's bounding area (0-100). */
  x: number;
  y: number;
}

export const techNodes: TechNode[] = [
  // Large — primary/daily tools
  {
    name: "React",
    icon: SiReact,
    color: "#61DAFB",
    size: "large",
    note: "My primary library for building interfaces.",
    pairsWith: ["Next.js", "Framer Motion", "GSAP", "Node.js", "Git"],
    x: 50,
    y: 42,
  },
  {
    name: "Next.js",
    icon: SiNextdotjs,
    color: "#FFFFFF",
    size: "large",
    note: "My default framework for shipping production apps.",
    pairsWith: ["React", "Node.js", "Express", "Git"],
    x: 33,
    y: 56,
  },
  {
    name: "Node.js",
    icon: SiNodedotjs,
    color: "#5FA04E",
    size: "large",
    note: "Runtime for every backend and API I build.",
    pairsWith: ["Next.js", "Express", "MySQL", "PostgreSQL", "Docker", "Git"],
    x: 67,
    y: 56,
  },
  {
    name: "Express",
    icon: SiExpress,
    color: "#FFFFFF",
    size: "large",
    note: "My go-to framework for REST APIs and services.",
    pairsWith: ["Node.js", "MySQL", "PostgreSQL", "Git"],
    x: 50,
    y: 70,
  },

  // Medium — frequently used
  {
    name: "Framer Motion",
    icon: SiFramer,
    color: "#0055FF",
    size: "medium",
    note: "Go-to for micro-interactions and page transitions.",
    pairsWith: ["React", "GSAP", "Storybook", "Git"],
    x: 21,
    y: 30,
  },
  {
    name: "GSAP",
    icon: SiGreensock,
    color: "#88CE02",
    size: "medium",
    note: "For scroll-scrubbed and timeline-based animation.",
    pairsWith: ["React", "Framer Motion", "Git"],
    x: 79,
    y: 30,
  },
  {
    name: "MySQL",
    icon: SiMysql,
    color: "#4479A1",
    size: "medium",
    note: "Relational storage for most of my client projects.",
    pairsWith: ["Node.js", "Express", "Docker", "Git"],
    x: 29,
    y: 80,
  },
  {
    name: "PostgreSQL",
    icon: SiPostgresql,
    color: "#4169E1",
    size: "medium",
    note: "My pick when a project needs stronger data guarantees.",
    pairsWith: ["Node.js", "Express", "Docker", "Git"],
    x: 71,
    y: 80,
  },
  {
    name: "TypeScript",
    icon: SiTypescript,
    color: "#3178C6",
    size: "medium",
    note: "Every line I write, frontend or backend, is typed.",
    pairsWith: ["React", "Next.js", "Node.js", "Express", "Git"],
    x: 50,
    y: 26,
  },
  {
    name: "Tailwind CSS",
    icon: SiTailwindcss,
    color: "#06B6D4",
    size: "medium",
    note: "My default styling approach for every production interface.",
    pairsWith: ["React", "Next.js", "Storybook", "Git"],
    x: 50,
    y: 84,
  },

  // Small — tools/supporting
  {
    name: "HTML",
    icon: SiHtml5,
    color: "#E34F26",
    size: "small",
    note: "The markup foundation everything renders to.",
    pairsWith: ["CSS", "Git"],
    x: 10,
    y: 56,
  },
  {
    name: "CSS",
    icon: SiCss,
    color: "#1572B6",
    size: "small",
    note: "The styling layer under every interface I ship.",
    pairsWith: ["HTML", "Git"],
    x: 90,
    y: 56,
  },
  {
    name: "Storybook",
    icon: SiStorybook,
    color: "#FF4785",
    size: "small",
    note: "Where I build and document components in isolation.",
    pairsWith: ["React", "Framer Motion", "Git"],
    x: 16,
    y: 12,
  },
  {
    name: "CI/CD",
    icon: SiGithubactions,
    color: "#2088FF",
    size: "small",
    note: "Automated testing and deploys on every push.",
    pairsWith: ["Docker", "Git"],
    x: 84,
    y: 12,
  },
  {
    name: "Docker",
    icon: SiDocker,
    color: "#2496ED",
    size: "small",
    note: "Containerizing services for consistent environments.",
    pairsWith: ["Node.js", "MySQL", "PostgreSQL", "CI/CD", "Git"],
    x: 50,
    y: 16,
  },
  {
    name: "Git",
    icon: SiGit,
    color: "#F05032",
    size: "small",
    note: "Version control for every project, no exceptions.",
    pairsWith: [
      "React",
      "Next.js",
      "Node.js",
      "Express",
      "Framer Motion",
      "GSAP",
      "MySQL",
      "PostgreSQL",
      "HTML",
      "CSS",
      "Storybook",
      "CI/CD",
      "Docker",
    ],
    x: 50,
    y: 94,
  },
  {
    name: "NestJS",
    icon: SiNestjs,
    color: "#E0234E",
    size: "small",
    note: "Structured Node.js framework for larger service architectures.",
    pairsWith: ["Node.js", "TypeScript", "PostgreSQL", "Git"],
    x: 33,
    y: 9,
  },
  {
    name: "JWT",
    icon: SiJsonwebtokens,
    color: "#FB015B",
    size: "small",
    note: "Auth tokens and refresh-rotation behind every login flow I build.",
    pairsWith: ["Node.js", "Express", "NestJS", "Git"],
    x: 67,
    y: 9,
  },
  {
    name: "Redis",
    icon: SiRedis,
    color: "#DC382D",
    size: "small",
    note: "Caching, sessions, and pub/sub for real-time features.",
    pairsWith: ["Node.js", "NestJS", "Docker", "Git"],
    x: 8,
    y: 42,
  },
  {
    name: "TanStack Query",
    icon: SiReactquery,
    color: "#FF4154",
    size: "small",
    note: "Server-state caching, pagination, and sync on the frontend.",
    pairsWith: ["React", "Next.js", "TypeScript", "Git"],
    x: 92,
    y: 42,
  },
  {
    name: "MongoDB",
    icon: SiMongodb,
    color: "#47A248",
    size: "small",
    note: "Document storage for flexible, less relational data.",
    pairsWith: ["Node.js", "NestJS", "Git"],
    x: 14,
    y: 70,
  },
  {
    name: "RabbitMQ",
    icon: SiRabbitmq,
    color: "#FF6600",
    size: "small",
    note: "Message queues for background jobs and service decoupling.",
    pairsWith: ["Node.js", "NestJS", "Docker", "Git"],
    x: 86,
    y: 70,
  },
  {
    name: "MinIO",
    icon: SiMinio,
    color: "#C72E49",
    size: "small",
    note: "S3-compatible object storage for uploads and media.",
    pairsWith: ["Node.js", "Docker", "Git"],
    x: 10,
    y: 90,
  },
  {
    name: "Jest",
    icon: SiJest,
    color: "#C21325",
    size: "small",
    note: "Unit and integration tests for critical application logic.",
    pairsWith: ["TypeScript", "Node.js", "Git"],
    x: 90,
    y: 90,
  },
  {
    name: "Zod",
    icon: SiZod,
    color: "#3E67B1",
    size: "small",
    note: "Runtime schema validation at every API and form boundary.",
    pairsWith: ["TypeScript", "React", "Node.js", "Git"],
    x: 6,
    y: 20,
  },
  {
    name: "Figma",
    icon: SiFigma,
    color: "#F24E1E",
    size: "small",
    note: "Where I read designs and turn them into production interfaces.",
    pairsWith: ["React", "Storybook", "Git"],
    x: 94,
    y: 20,
  },
];
